#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    swaps=0
    for i in range(0,n):
        for j in range(0,n-1):
            if a[j]>a[j+1]:
                x=a[j]
                a[j]=a[j+1]
                a[j+1]=x
                swaps+=1
            else:
                continue
        if swaps == 0:
            break
    print(f"Array is sorted in {swaps} swaps. ")
    print("First Element: "+ str(a[0]))
    print("Last Element: "+ str(a[len(a)-1]))
